- Cargo.toml
- src/client/client.rs
- src/client/mod.rs
- src/client/pool.rs
- src/common/exec.rs
- src/common/mod.rs
- src/error.rs
- src/lib.rs
I'm giving https://github.com/hyperium/hyper/issues/2860 a go, but I'm not sure I'm going in the right direction.
Appreciate if you could take a look when you have time @seanmonstar 
---
Some questions:
Some part of `pool` uses `hyper::Errors`
```log
error[E0624]: associated function `new_canceled` is private
--> src/client/pool.rs:592:41
|
592 | ...                   HyperError::new_canceled().with(CheckoutIsClosedError)
|                                   ^^^^^^^^^^^^ private associated function
|
:::
|
247 |     pub(super) fn new_canceled() -> Error {
|     ------------------------------------- private associated function defined here
```
I'd imagine that it's probably best to expose these functions from `hyper::Error`, but I'm not sure that this would follow the plan for `hyper-util`?
> feat(pool): import client::pool from hyper

- src/lib.rs
- src/rt/mod.rs
- src/rt/tokio_executor.rs
Hey Sean,
I decided to give https://github.com/hyperium/hyper/issues/2861 a go. I'd like to ramp up the contributions after that.
Not certain what exactly is required, feel free to require additional changes.
I tried to write some basic test, but I don't know of a good way to wait for a spawned task without retaining the handle.
Also, I have a question. Why does the `Executor` trait require a generic parameter, wouldn't it make sense to only require it on `execute` function? I.e.:
```
fn execute<Fut>(&self, fut: Fut)
```
Closes https://github.com/hyperium/hyper/issues/2861
> feat(rt): add TokioExecutor

- Cargo.toml
- src/client/connect/http.rs
- src/client/connect/mod.rs
- src/client/pool.rs
- src/common/mod.rs
- src/common/never.rs
Closes https://github.com/hyperium/hyper-util/issues/7.
This PR:
* add missing feature flags that were referenced in code, but not in `Cargo.toml`: `runtime`, `tcp`, `http1`, `http2`
* copies `Never` struct from `hyper` and uses it in `client` module to make it compile when features are enabled
* fixes 3 Clippy warnings about preferring `Copy` to `Clone`
There is one test still failing: `client::connect::http::tests::client_happy_eyeballs`. It's a bit over my head, so I didn't attempt to fix it.
> fix: add missing feature flags

- src/common/mod.rs
This avoids linter errors when not using the runtime feature
> Only export `Never` with associated features

- src/client/pool.rs
This PR makes pooling generic over the Key type, so the caller can decide how they wish to pool the client connections.
This PR builds on the work done by @EItanya (my colleague who is going OOO for a bit, so I took over) in https://github.com/hyperium/hyper-util/pull/12.
Since that PR, support for the `runtime` feature was introduced, and a blanket impl was added for Key (see https://github.com/hyperium/hyper-util/pull/12#discussion_r1049919896).
With this and https://github.com/hyperium/hyper-util/pull/15 pulled locally, I was able to get a full custom pooling implementation in our project. edit: actually only can pool with `Reservation::Unique` at this point since SendRequest isn't `Clone` and `into_http2()` is private. But those can be addressed I think.
> pool: introduce generic Key parameter

- src/client/client.rs
- src/client/pool.rs
- src/common/mod.rs
Currently `pool` is not pub, and nothing `pub` uses it, so it isn't accessible. This exposes them for use.
Discussed here: https://discordapp.com/channels/500028886025895936/670880858630258689/1053021031805227109
> pool: make relevant items `pub`

- src/client/legacy.rs
- src/client/mod.rs
Legacy Client's feature config seems not correct, and example has compile error.
> Fix legacy client feature config

- Cargo.toml
In CI MSRV is set to 1.56. It seems lock once_cell to 1.14 is not necessary，and this lock cause conflict with many other crates.
> Unlock once_cell version

- src/client/connect/http.rs
This is a duplicate of https://github.com/hyperium/hyper/pull/3076 (which itself was a duplicate of https://github.com/hyperium/hyper/pull/2484).
If I understand hyper 1 correctly, then this essentially moves that PR from being against the `v0.14` branch to the `v1` branch.
> Add set_interface connector option

- .github/workflows/CI.yml
Updates ci configs.
- Updates to use actions/checkout@v3 from v1.
- Replaces actions-rs/toolchain with dtolnay/rust-toolchain as it is unmaintained.
- Replaces actions-rs/cargo with run as it is unmaintained.
- Replaces `cargo install` with taiki-e/install-action to install cargo-hack to avoid compiling it every ci.
- Removes redundant step names.
> chore(ci): update ci config

- src/server/conn/auto.rs
We cannot assume that the client will definitely send 24 bytes.
- If the client closes the connection before sending 24 bytes, the loop will not exit, but will be awakened infinitely, causing the current thread to fill up the core of the current CPU.
- If the client does not disconnect but does not send the full 24 bytes, it cannot be determined whether it is http1 or http2, resulting in infinite waiting. For example:
```rust
use std::{net::{TcpStream},io::{Error, Write, Read}};
fn main()->Result<(),Error> {
let mut conn = TcpStream::connect("127.0.0.1:5800")?;
println!("connection ok");
let write_content = b"GET / HTTP/1.1\r\n\r\n";
conn.write(write_content)?;
println!("write ok");
let mut vec = Vec::new();
vec.resize(1024 * 1024, b'\0');
let read_size = conn.read(& mut vec[..])?; …
```
> fix: auto conn infinite loop if conn closed before send full bytes

- .github/workflows/CI.yml
- Cargo.toml
- src/server/conn/auto.rs
Replaces `std::task::ready` with `futures_util::ready`, as the former requires Rust 1.64, which is larger than `hyper-util`'s MSRV 1.63.
> fix: replace std::task::ready with futures_util::ready

- src/server/conn/auto.rs
In all honesty, I really don't know if it's possible to have this happen in the same function with a `?Send` way, but I couldn't get that to work. So I added a new function that requires the IO stream to be `Send`, which automatically upgrades HTTP/1 connections.
Also, does HTTP/2 not require upgrades? I was looking for a similar `.with_upgrades()` function in `self.http2.serve_connection`, and when I couldn't find it, I tried adding it, and realized that there was no `upgrades` module at all. Is this inherently present in HTTP/2 or is this just something that we haven't implemented yet?
This is required by tokio-rs/axum#2241
> Added `.with_upgrades()` to connection

- src/client/pool.rs
- src/common/mod.rs
Replaces `Never` with `std::convert::Infallible` as with https://github.com/hyperium/hyper/pull/3335.
> refactor(common): replace Never with Infallible

- .github/workflows/CI.yml
Uses `cargo-hack`'s `--no-dev-deps` option to check without dev-dependencies as with https://github.com/hyperium/hyper/pull/3342.
> chore(ci): use cargo-hack --no-dev-deps option to check without dev-dependencies

- src/server/conn/auto.rs
The current bounds appear to be too strict when it comes to `Send`ness, preventing the usage of `auto` in combination with an implementation of `Executor` that's designed to spawn `!Send` futures.
> Drop Send requirements on the future returned by the service

- Cargo.toml
The `once_cell` crate version config seems not to be needed now.
> chore(dependencies): remove once_cell crate version config

- src/client/legacy.rs
Currently, a timer must be provided to use http2. However, this has no option to actually configure this. This PR introduces a new function to set the timer. With this, I am able to successfully make HTTP2 calls with the Client (as long as there is no error - currently we hit a todo!() on errors)
> client: add timer() option

- src/client/legacy.rs
- src/client/pool.rs
Alternative to https://github.com/hyperium/hyper-util/pull/24.
Currently, `Pool` cannot be used at all. It requires a concrete `Exec`, and that is private. The #24 PR simply made `Exec` public. However, there is already other things in this crate that require an `Exec` (`legacy::Client`).
This adapts `Pool` to follow the same pattern as used for `Client`, taking in a trait.
This change is NOT a breaking change, as `Pool` cannot be used at all currently, so no one could be broken.
> pool: use `Executor` trait instead of concrete type

- src/client/legacy/mod.rs
Since #49, we cannot refer to the Error response from the client. This exposes it again
> Re-expose connect::Error after #49

- Cargo.toml
The documentation on docs.rs is empty at the moment, which is not very useful.
This PR enables the `full` feature flag when building docs for docs.rs to make sure all items are documented.
> Enable all feature flags when generating docs for docs.rs

- Cargo.toml
As it currently stands, enabling `server-auto` doesn't actually give you access to any new item _unless_ you also enable the `server` feature.
Considering how the code is structured, I think that the `server-auto` feature flag should imply the `server` feature flag.
> Feature flags: `server-auto` should imply `server`

- Cargo.toml
Without this, I see
```rust
error[E0599]: no method named `bind_device` found for struct `Socket` in the current scope
--> /home/jayvdb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-util-0.1.1/src/client/legacy/connect/http.rs:704:14
|
703 | /         socket
704 | |             .bind_device(Some(interface.as_bytes()))
| |             -^^^^^^^^^^^ method not found in `Socket`
| |_____________|
| 
error[E0599]: no method named `with_retries` found for struct `TcpKeepalive` in the current scope
--> /home/jayvdb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-util-0.1.1/src/client/legacy/connect/http.rs:130:12
|
130 |         ka.with_retries(retries)
|            ^^^^^^^^^^^^ help: there is a method with a similar name: `with_time`
For more information about this …
```
> Add socket2 feature "all"

- src/lib.rs
- src/service.rs
Extracted from https://github.com/hyperium/hyper-util/pull/46. This adds `TowerToHyperService` which converts a tower service into a hyper service. Among other things, this is useful for running axum with hyper.
> feat: add `TowerToHyperService`

- src/server/conn/auto.rs
Being able to create a single builder, which then can be cloned to enable reuse would be ideal. Also implements `Debug` for the builder.
> feat: make builder clonable

- src/rt/mod.rs
- src/rt/tokio.rs
In the latest master branch of `hyper` the `hello` server example has been changed to include a `TokioTimer`.
This exists in `hyper`'s `support` module, but does not yet exist in `hyper-util`.
This PR adds that functionality by copying over the implementation from `hyper`.
Similar to `TokioExecutor` in this repo. It can only be created through the `new` constructor. This differs from `hyper`'s `support` module, where both `TokioExecutor` and `TokioTimer` are directly creatable as an empty struct.
> feat: Add TokioTimer to rt::tokio module

- src/client/legacy/connect/http.rs
from hyper 0.14.x
commit：https://github.com/hyperium/hyper/pull/3355
> fix(http): divide by zero error when dividing duration by scalar

- Cargo.toml
- src/lib.rs
- src/service.rs
The `tower/tower-service` is only used in the `client/client-legacy` feature. If one only needs `server/server-auto` feature, there is no need to include them.
Testing in sigoden/dufs#321,  with this pr, there is a reduction of 0.3 M in the stripped release binary.
> feat: tower should be an optional dependency

- Cargo.toml
- src/server/conn/auto.rs
This PR aims to unblock axum adding some kind of graceful shutdown convenience API. A somewhat common complaint with axum 0.7 is that graceful shutdown is more complicated than it was with `hyper::Server`.
axum provides a basic [`serve`](https://docs.rs/axum/latest/axum/fn.serve.html) function that needs to support both http1 and http2. Therefore we use hyper-utils "auto conn" but that doesn't support graceful shutdown.
This PR aims to implement a minimal way to unblock that without having write a whole new server type:
- Instead of  [`hyper_util::server::conn::auto::Builder::serve_connection_with_upgrades`](https://docs.rs/hyper-util/latest/hyper_util/server/conn/auto/struct.Builder.html#method.serve_connection) being an `async fn` that returns an opaque future, return something that …
> Support graceful shutdown on "auto conn"

- src/server/conn/auto.rs
Load testing on our web application caused issues and it looks like it is because of this.
The default value is 200 as you can see from the default instantiation here: https://github.com/hyperium/hyper/blob/1d4ff3597b8e76818c8553dbfa4234cf4208c958/src/proto/h2/server.rs#L66
> Document the correct default value

- src/client/legacy/client.rs
- src/client/legacy/pool.rs
fixes https://github.com/hyperium/hyper/issues/3499
This PR fixes the `hyper_util::client::legacy::Client` always returning an error without sending any request.
Found while working on https://github.com/hyperium/hyper-util/pull/77, test for this will be included in the PR.
---
After the change, the code in the issue returns
```rust
Ok(
Response {
status: 200,
version: HTTP/1.0,
headers: {
"server": "SimpleHTTP/0.6 Python/3.11.4",
"date": "Fri, 22 Dec 2023 13:24:20 GMT",
"content-type": "text/html; charset=utf-8",
"content-length": "2204",
},
body: Body(
Streaming,
),
},
)
```
instead of `PoolDisabled` error
> fix(client): no keep-alive always returning an error

- .github/workflows/CI.yml
- Cargo.toml
- src/rt/tokio.rs
- tests/legacy_client.rs
- tests/test_utils/mod.rs
part of https://github.com/hyperium/hyper/issues/2942
> feat: port legacy client integration tests

- src/client/legacy/pool.rs
- src/common/mod.rs
`hyper-util` could use `futures_util::ready`.
> chore: use futures_util::ready

- src/client/legacy/client.rs
- src/client/legacy/pool.rs
- src/common/mod.rs
- src/common/timer.rs
Addresses https://github.com/hyperium/hyper/issues/3167
Note that previously we're using tokio's `Interval` rather than `Sleep`. This PR tries to emulate the behavior for `Pool` using `Sleep` instead, so that:
1. No extra trait for `Interval`
2. User only needs to supply a `Timer` rather than a `Timer` and also an `Interval`.
> feat: add timer support for `legacy::Pool`

- src/client/legacy/client.rs
- src/client/legacy/connect/http.rs
- src/client/legacy/pool.rs
- src/server/conn/auto.rs
Applies some small refactoring.
> refactor(client): small refactoring

- src/client/legacy/client.rs
It will be useful for reqwest's upgrade to hyper v1.
> feat: Add a `Error::is_connect()` method

- Cargo.toml
- src/server/conn/auto.rs
- src/server/conn/mod.rs
As in the title. Previously we pulled in just the deps for http1 or just the deps for http2. This reenables that.
> feat: allow enabling http1/http2 individually

- Cargo.toml
- src/client/legacy/client.rs
This adds `initial_max_send_streams` method to the client builder. This simply calls the method with the same name defined in `hyper::client::conn::http2::Builder`.
Depends on https://github.com/hyperium/hyper/pull/3524
> feat(http2): add `initial_max_send_streams` method to client builder

- Cargo.toml
- src/server/conn/auto.rs
This adds `max_pending_accept_reset_streams` method to the server builder.
Closed: https://github.com/hyperium/hyper/issues/3461
Depends on https://github.com/hyperium/hyper/pull/3507
Continue for: https://github.com/hyperium/hyper-util/pull/78
> Max pending accept reset streams

- Cargo.toml
`socket2` dependency is only used in the client-legacy.
Current approach had the disadvantage of enabling socket2 even if you don't need it, e.g. a platform that socket2 doesn't support like `wasm-unknown-unknown`
> fix: enable socket2 only for client-legacy

- src/server/conn/auto.rs
I've added a test that checks that a connection that has not written anything is closed in a timely manner.
I've checked that the test would have failed with a timeout before this has been fixed.
Closes [#3582](https://github.com/hyperium/hyper/issues/3582)
> tests: add teest for graceful shutdown

- src/client/legacy/client.rs
- src/server/conn/auto.rs
This PR adapts configurable `max_headers` by hyperium/hyper#3523.
> feat: adapt configurable `max_headers`

- Cargo.toml
- examples/server.rs
This may help to alleviate https://github.com/hyperium/hyper/issues/3560.
> add an example showing how to make a server

- Cargo.toml
`hyper-util` implicitly depends on `tower`'s feature `log` through `default`s, which should not be necessary. They have [long since removed the defaults](https://github.com/tower-rs/tower/commit/5064987ffec4420ef6ea6de649606286370e42bc), but never actually released a new version with that fix.
I have only found this because i upgraded to reqwest 0.12 (from 0.11), which suddenly spammed the logs (which were not setup for tracing yet) with tracing output, but those logs could somehow not be disabled, and finding the cause was quite annoying. This all happened because `tower`'s `log` feature sets `tracing/log`.
> fix: disable default features for dep "tower"

- src/rt/tokio.rs
The `TokioIo` docs are confusing when a user intends to use it for adapting a hyper IO trait impl to a Tokio IO trait impl. This commit updates the `TokioIo` docs to make clear that it is a bidirectional adapter between Tokio's and hyper's IO traits.
> doc: Fix `TokioIo` doc

- src/client/legacy/connect/http.rs
Without this implementation, when a downstream crate wants to implement a custom `HttpConnector`, it would have to wrap up an extra layer over `TokioIo<TcpStream>`. Consequently, this would result in a forwarding implementation of `hyper::rt::{Read, Write}` for the new type.
See [here](https://github.com/kvinwang/wapo/commit/9e748d401128101efe05098f740a65b1549771ca) for more detail.
> feat: impl Connection for TokioIo

- src/server/conn/auto.rs
Hello!
Thanks for this crate, I've been using it with axum since converting to hyper 1.0.
However I had been using it with default values, and after https://seanmonstar.com/blog/hyper-http2-continuation-flood/ I wanted to set max_header_list_size as suggested, and realized I couldn't call .serve_connection_with_upgrades with that (I've seen `serve_connection().with_upgrades()` in another part of the code but that doesn't seem to make sense with this one that returns a future `Result<()>` -- and not using with_upgrades means I cannot create websockets anymore so that's not an option either)
Happy to rework it otherwise, or if that's easier let someone else implement something different (or just tell me I could use xyz in my code!) and drop this.
Cheers,
--------------
When using …
> feat(conn/auto): allow serving connection with upgrade after config

- Cargo.toml
- src/client/legacy/client.rs
- src/client/legacy/connect/capture.rs
- src/client/legacy/connect/mod.rs
- tests/legacy_client.rs
This is backport (frontport?) of https://github.com/hyperium/hyper/pull/3144 into hyper-util. This pairs with connection poisoning to allow callers more control over connections in the pool.
> feat(client): Add connection capturing API to hyper-util

- src/client/legacy/client.rs
Adds this missing function to the legacy client.
#90 was merged with half of #78. This PR is the other half.
> Adds `max_pending_accept_reset_streams` for legacy

- src/client/legacy/client.rs
- src/client/legacy/connect/http.rs
Replaces deprecated numeric api with primitive one.
> refactor(client): replace deprecated numeric api with primitive one

- .github/workflows/CI.yml
- Cargo.toml
Cargo.toml supports MSRV - https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field
cc @seanmonstar
> Config rust-version at Cargo.toml

- src/server/conn/auto.rs
I noticed when trying to make use of #127 that you cannot currently create and reuse a server builder, and spawn the connections into a new task, because `Connection` borrows the `Builder`. (In hindsight, it probably should have just made a clone, but oh well.) This adds the ability to disconnect the lifetimes.
> feat: add auto Connection::into_owned

- Cargo.toml
- examples/server_graceful.rs
- src/server/graceful.rs
- src/server/mod.rs
This adds a new `hyper_util::server::graceful::GracefulShutdown` helper, which can be used to watch connections, and then trigger a graceful shutdown and await all connections finishing.
Continues off of #108. cc @glendc
Closes https://github.com/hyperium/hyper/issues/2862
> feat: add GracefulShutdown helper

- Cargo.toml
Updates to the latest version of `pnet_datalink`.
https://github.com/libpnet/libpnet/releases/tag/v0.35.0
> chore: update to pnet_datalink 0.35.0

- src/server/graceful.rs
This PR removes the unnecesary `watch::Receiver<()>` field from the `GracefulShutdown` struct.
The receiver field is unnecesary since a Receiver can be obtained with `Sender::subscribe()`.
This reduces the size of the struct from 24 to 8.
After this is merged we can think if its worth it to enable `Clone` of the `GracefulShutdown`, which will produce a more flexible api for consumers.
> fix: remove unnecesary receiver field from GracefulShutdown

- src/client/legacy/client.rs
See <https://github.com/hyperium/hyper/pull/2749>.
> Restore connect info in errors

- .github/workflows/CI.yml
Uses `tokio` 1.38.1 in the MSRV checking as `tokio` 1.39 bumps its MSRV to 1.70.
https://github.com/tokio-rs/tokio/releases/tag/tokio-1.39.0
> chore(ci): Use tokio 1.38.1 in MSRV check

- src/client/legacy/client.rs
- src/client/legacy/connect/mod.rs
- tests/legacy_client.rs
This is a port of https://github.com/hyperium/hyper/pull/3145/files + a test.
It introduces a `PoisonPill` atomic onto connection info. When set to true, this prevents the connection from being returned to the pool.
> Add API for poisoning connections

- src/client/legacy/connect/http.rs
Ignore dead code warnings for interface fields on unsupported platforms
> feat(http): Add conditional compilation for `interface` field in Config struct.

- Cargo.toml
- src/common/rewind.rs
- src/server/conn/auto/mod.rs
- src/server/conn/auto/upgrade.rs
This fixes <https://github.com/hyperium/hyper/issues/3704>.
> Introduce hyper_util::server::conn::auto::upgrade::downcast

- src/client/legacy/client.rs
In migrating to hyper v1, we encountered an issue with reqwest that we tracked down to hyper-util. I've created a reproduction [here](https://github.com/ahl/hyper-util-retry-repo).
We see what appears to be aberrant behavior when a client (`reqwest::Client` or `hyper_util::client::legacy::Client`) is making a request to a server that may close the connection deliberately. In particular, we see that the client opens a new connection and may try opening connections many many times! If the client is unable to start writing the request to the newly opened connection, it will open a new connection and try again until it's able to write some or all of the request to the socket prior to the server closing it.
This appears to be a result of #133 which reintroduced retry logic. It is quite similar …
> fix erroneous retries on a failed request to a newly opened socket

- Cargo.toml
- src/client/legacy/connect/mod.rs
- src/lib.rs
- src/service/glue.rs
- src/service/mod.rs
- src/service/oneshot.rs
Closes https://github.com/hyperium/hyper/issues/3757
> chore: remove tower dep by vendoring Oneshot

- src/client/legacy/connect/http.rs
Setting TCP keepalive is not enough to prevent dead TCP connections.
See https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/
I'm adding this to the "legacy" HTTP client because my goal is to add the setting to Tonic which is still using the `HttpConnector`.
> Add a new config to set TCP_USER_TIMEOUT

- src/client/legacy/client.rs
Currently the max size of received header frames for HTTP2 responses defaults to the 16KB when creating a hyper client. The 16KB default is defined in [hyper::proto::h2::DEFAULT_MAX_HEADER_LIST_SIZE](https://github.com/hyperium/hyper/blob/master/src/proto/h2/client.rs#L54).
This PR adds support to override this default value, to allow for custom limits of the maximum header sizes being received in HTTP/2 responses.
Adjusting the limit is already supported for incoming requests with [hyper_util::server::conn::auto::Http2Builder::max_header_list_size](https://docs.rs/hyper-util/latest/hyper_util/server/conn/auto/struct.Http2Builder.html#method.max_header_list_size).
> feat(client): Expose `http2::builder::max_header_list_size` in the client builder

- src/common/rewind.rs
On current master (`30f38c8d8728ee99a2194bc7a2c5f556cb6a0a3a`) with Rust 1.82 (`rustc 1.82.0 (f6e511eec 2024-10-15)`, `cargo 1.82.0 (8f40fc59f 2024-08-21)`), running `cargo check --all-features --tests` emits the following warning:
```
warning: associated items `new` and `rewind` are never used
--> src/common/rewind.rs:20:19
|
18 | impl<T> Rewind<T> {
| ----------------- associated items in this implementation
19 |     #[cfg(test)]
20 |     pub(crate) fn new(io: T) -> Self {
|                   ^^^
...
36 |     pub(crate) fn rewind(&mut self, bs: Bytes) {
|                   ^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: `hyper-util` (lib test) generated 1 warning
```
This PR fixes that and also does some other, opportunistic cleanup in the same file:
- Removes unused `new` …
> chore: Fix test warning

- src/client/legacy/connect/capture.rs
- src/client/legacy/connect/dns.rs
- src/client/legacy/connect/http.rs
- src/server/conn/auto/mod.rs
- src/server/conn/auto/upgrade.rs
On current master (`a63603772ee1bc98957cf86eb3a904ed2357ba36`) with Rust 1.82 (`rustc 1.82.0 (f6e511eec 2024-10-15)`, `cargo 1.82.0 (8f40fc59f 2024-08-21)`), although both running `cargo doc` and running `cargo check --all-features` works without warnings, running `cargo doc --all-features` emits the following warnings:
<details><summary>Warnings</summary>
```
warning: unresolved link to `crate::client::connect::dns`
--> src/client/legacy/connect/http.rs:171:30
|
171 |     /// Takes a [`Resolver`](crate::client::connect::dns#resolvers-are-services) to handle DNS lookups.
|                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no item named `connect` in module `client`
|
= note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
warning: unresolved link to …
```
> chore: Fix docs warnings when docs built with `--all-features`

- .github/workflows/CI.yml
Uses `hashbrown` 0.15.0 in MSRV checking as `hashbrown` 0.15.1 bumps its MSRV to 1.65.
> chore(ci): Use hashbrown 0.15.0 in MSRV check

- src/server/conn/auto/mod.rs
- src/server/graceful.rs
> chore: Remove needless lifetime

- src/client/legacy/client.rs
Doing a bit of cleanup, this race condition was closed back in 2021.
Ref: https://github.com/rust-lang/futures-rs/issues/909
> chore: remove legacy::client workaround for fixed race condition in mpsc channel

- src/client/legacy/connect/http.rs
This shoud fixe https://github.com/hyperium/hyper/issues/3817
> fix: Align the cfg compilation with the `socket2`

- src/server/conn/auto/mod.rs
When utilizing TLS, a user must know if they have their server configured to handle HTTP/1.1 and/or HTTP/2 to properly determine which protocols can be negotiated over ALPN.
This PR adds two new methods to `hyper_util::server::conn::auto::Builder`: `is_http1_available` and `is_http2_available`, which tie back to the inner version value used to determine how to serve a connection. In exposing these, users can now programmatically build the ALPN protocol list rather than having to hardcode it, potentially ending up with a mismatch between the hardcoded list and the actual feature flags enabled for `hyper`/`hyper-util`.
> builder: expose methods for determining if HTTP/1.1 or HTTP/2 support are enabled

- Cargo.toml
- src/server/conn/auto/mod.rs
This PR adds `hyper-util` builder support for functions that were previously missing:
- HTTP/1 `ignore_invalid_headers` (`hyper` 1.6.0)
- HTTP/1 `auto_date_header` (`hyper` 1.4.0)
- HTTP/2 `auto_date_header` (`hyper` 1.4.0)
- HTTP/2 `max_local_error_reset_streams` (`hyper` ~~1.2.0~~ 1.6.0)
Function signatures, function order, and function documentation are copied from `hyper`.
~~**Draft because blocked on: https://github.com/hyperium/hyper/pull/3820**~~
> feat(server): support `auto_date_header`, `max_local_error_reset_streams`, and `ignore_invalid_headers`.

- Cargo.toml
- src/rt/tokio.rs
Hi Sean! :wave: 
The tracing span context set in consumers of the `TokioExecutor` is sometimes lost (if the task is run in a different thread). This change adds a call to `in_current_span()` to preserve it.
As a side-effect, it adds a dependency on tracing for the tokio feature. Should I instead allow the new behavior only if tracing is enabled? Or use a separate `TracingExecutor` for this?
> fix(tracing): propagate span context

- src/rt/tokio.rs
there is a module-wide allowance for dead code that seems to be a holdover from when this was initially being written.
removing this does not unearth any warnings, and ideally any future additions can be explicitly, and more narrowly, annotated accordingly if need be.
> chore(tokio): warn on dead code

- src/client/legacy/client.rs
this function is not used, and a warning is observed when this crate is built with e.g. `--all-features`.
this commit removes this unused method from the `PoolClient<B>` type.
> chore(client/legacy): remove unused `PoolClient::is_closed()`

- Cargo.toml
- src/client/legacy/connect/http.rs
The `client::legacy::connect::HttpConnector` type has a method
`set_interface` that configures the connector to bind TCP connections
only on the provided interface name. Presently, this is enabled only on
Linux, Android, and Fuchsia, as it uses the Linux-only socket option
[`SO_BINDTODEVICE`].
[On macOS] (and other Apple operating systems such as iOS, watchOS,
etc), [and Solaris] and Solaris-like systems like illumos, the Solaris
socket option [`IP_BOUND_IF`] provides similar functionality to
`SO_BINDTODEVICE`, as it also restricts connections to a particular
network itnerface. Unlike the Linux socket option, `IP_BOUND_IF` takes
the numeric _index_ of the interface, so in order to accept a string
interface name similarly to the Linux implementation, we must use
[`if_nametoindex(3socket)`] …
> enable `HttpConnector::interface` on macOS and Solarish systems

- src/server/conn/auto/mod.rs
- Mark `serve_connection` and `serve_connection_with_upgrades` as `must_use` to prevent ignored results.  
- Mark `serve_connection_with_upgrades` as `must_use` for consistency.  
- Helps avoid silent issues when forgetting to `.await` the connection.  
Not a major issue, but spent 15 minutes debugging due to a missing `.await`.
> fix(server): Enforce `serve_connection` result usage

- src/client/legacy/connect/dns.rs
`tracing` has an unresolved bug when attempting to fetch a span that _should_ exist. Tracking: https://github.com/tokio-rs/tracing/issues/3223#issuecomment-2771038993
#134 introduces this bug. `hyper` contributors aren't at fault — this is a `tracing` issue.
As a result, crates that depend on `hyper`'s legacy client (e.g. `reqwest`) will immediately panic when a request is sent under specific circumstances configured by `tracing` spans. (The tracked comment shows a pseudocode example). This slightly more accurate `tracing` span is not worth the panics. 
In theory, this PR can be reverted once `tracing` resolves this issue, but its up to the maintainers whether or not it should be prioritized.
> fix(tracing): revert #134 - tracing span removal in legacy DNS `GaiResolver`

- src/common/rewind.rs
Removes two uses of unsafe by using native `ReadBufCursor` methods instead of the duplicated implementations.
I'm so happy cargo-geiger is back :smiley:.
> refactor: replace manual implementations of `ReadBufCursor` methods

- src/server/graceful.rs
This allows creating an owned type that can be passed to another task before `watch`ing the connection.
I also included some of the "why" in code comments, why it cannot just be `Clone`.
Supercedes #136
> feat(server): add graceful::Watcher type

- src/server/conn/auto/mod.rs
This allows to use default trait to create a builder when the used executor implements default.
> feat(server): implement default for server auto connection builder

- src/client/legacy/connect/mod.rs
- src/client/legacy/connect/proxy/mod.rs
- src/client/legacy/connect/proxy/tunnel.rs
- src/rt/io.rs
- src/rt/mod.rs
- tests/proxy.rs
cc https://github.com/hyperium/hyper/issues/3851
> feat(client): add `proxy::Tunnel` legacy util

- src/client/legacy/client.rs
The example (/doctest) uses a pool idle timeout, which according to the docs doesn't actually do anything without a pool timer.
Including a timer makes this example less misleading.
> docs(client): Include .pool_timer() in the Client builder example

- src/server/graceful.rs
This adds a method to get the number of the watching connections, which is useful mainly for the debug purpose.
> feat(server): add method to get number of watching connection

- Cargo.toml
- src/client/mod.rs
- src/client/proxy/matcher.rs
- src/client/proxy/mod.rs
cc https://github.com/hyperium/hyper/issues/3850
> Add a proxy Matcher

- Cargo.toml
- src/client/proxy/matcher.rs
The added code is mostly ported from `reqwest::proxy`.
> feat(client): add macOS system proxy support for Matcher

- src/client/legacy/connect/proxy/mod.rs
- src/client/legacy/connect/proxy/socks/mod.rs
- src/client/legacy/connect/proxy/socks/v4/errors.rs
- src/client/legacy/connect/proxy/socks/v4/messages.rs
- src/client/legacy/connect/proxy/socks/v4/mod.rs
- src/client/legacy/connect/proxy/socks/v5/errors.rs
- src/client/legacy/connect/proxy/socks/v5/messages.rs
- src/client/legacy/connect/proxy/socks/v5/mod.rs
- tests/proxy.rs
cc hyperium/hyper#3851, hyperium/hyper#3877 hyperium/hyper-util#173
Adds `SocksV4` and `SocksV5` connectors with simple configuration for local and remote DNS. Supports SOCKSv5 user/pass authentication and allows optimistic message sending (not in RFC but supported by most servers) to reduce number of round-trips in SOCKSv5 handshake.
TODO:
> feat(client): add proxy::SocksV4 and proxy::SocksV5 connectors

- Cargo.toml
- src/client/legacy/client.rs
- src/client/legacy/connect/dns.rs
- src/client/legacy/connect/http.rs
- src/client/legacy/connect/proxy/tunnel.rs
- src/client/legacy/pool.rs
- src/common/future.rs
- src/common/mod.rs
- src/rt/io.rs
- src/server/conn/auto/mod.rs
- src/service/oneshot.rs
Enable non-trivial applications based on hyper + tokio without pulling in this heavyweight dependency. Keep MSRV 1.63 by using `ready!` from `futures_core` and polyfilling `poll_fn`.
Don't remove futures-util from the `client-legacy` code, because this would require re-implementing several non-trivial combinators.
> refactor: limit dependency futures-util to tests and client-legacy

- Cargo.toml
- src/client/legacy/client.rs
- tests/legacy_client.rs
Fix a race condition in the legacy HTTP client's connection setup where connection errors (e.g., TLS failures, unexpected server responses) were discarded, resulting in vague ChannelClosed errors.
https://github.com/seanmonstar/reqwest/issues/2649
> fix(client): race in connection errors propagation

- Cargo.toml
This version of [windows-registry](https://crates.io/crates/windows-registry) is [largely the same](https://github.com/microsoft/windows-rs/releases/tag/64) but greatly reduces your dependencies as it uses the tiny [windows-link](https://crates.io/crates/windows-link) crate for linking Windows imports rather than the older [windows-targets](https://crates.io/crates/windows-targets) crate that pulls down a bunch of large import libs.
> Update to `windows-registry` 0.5

- src/client/legacy/connect/http.rs
This pull request simplifies error handling in `src/client/legacy/connect/http.rs` by removing unnecessary `.into()` calls when assigning error messages and updating the `fmt::Display` implementation of `ConnectError` to directly use the message string. These changes improve code clarity and reduce redundant operations.
> style(client): Fix some clippy lints

- src/client/legacy/connect/dns.rs
This was changed in #194, but that change seems to be wrong. The resolver is allowed to express it's priority through the ordering.
See https://datatracker.ietf.org/doc/html/rfc6555#section-6 and https://github.com/curl/curl/issues/16718.
Closes https://github.com/hyperium/hyper/issues/3900
> fix(client): prefer resolver order always

- src/client/legacy/pool.rs
With an incredibly tiny idle timeout, that can cause the idle checker interval to trigger very frequently. It doesn't seem necessary, and so this can cap to a minimum. The connections will still be "expired" at the time the user indicated, and will be respected when `Pool::checkout` tries to use it. It just might not be completely reaped from the data structures until a few milliseconds later.
@cratelyn any thoughts? I think this is probably a good idea. The amount of time I wasn't too sure on, it's somewhat arbitrary. I figured 100ms, and then made it a little under just in case so nothing waits _longer_ than due to too much load. But I could be convinced of anything.
> fix(client): cap pool idle interval to a minimum

- src/client/legacy/connect/capture.rs
- src/client/legacy/connect/http.rs
- src/client/legacy/pool.rs
- src/rt/tokio.rs
- tests/legacy_client.rs
Some tests seem to be able to be run with miri.
> chore(test): remove some miri exception config
